"""Render per-repo INDEX.md and the umbrella PORTFOLIO.md."""
from __future__ import annotations
from datetime import date, datetime

import model

def _banner(today) -> str:
    return _BANNER.replace("-->", f"generated {today.isoformat()} -->")


_BANNER = ("<!-- generated by tools/plan-portfolio -- do not edit by hand; "
           "run `python3 tools/plan-portfolio/generate.py` -->")


def _prio(item) -> str:
    return item.priority or item.computed_priority or "--"


def _age(item, today) -> str:
    for s in (item.updated, item.created):
        if s:
            try:
                d = datetime.strptime(s.strip(), "%Y-%m-%d").date()
                return f"{(today - d).days}d"
            except ValueError:
                pass
    return "--"


def _sort_key(item):
    return (0 if item.status in model.ACTIVE_STATUSES else 1, _prio(item), item.path)


def _index_row(item, today) -> str:
    flags = ", ".join(item.flags) if item.flags else "--"
    return (f"| {item.title} | {item.doc_type} | {item.status} | {_prio(item)} "
            f"| {_age(item, today)} | {item.source or '--'} | {flags} |")


def render_repo_page(repo_name, items, today) -> str:
    rows = [_index_row(i, today) for i in sorted(items, key=_sort_key)]
    header = ("| Plan | Type | Status | Priority | Age | Source | Flags |\n"
              "|---|---|---|---|---|---|---|")
    body = "\n".join(rows) if rows else "_No plans found._"
    return (f"# {repo_name} -- Plan Index\n\n{_banner(today)}\n\n"
            "[<- all repos](PORTFOLIO.md)\n\n"
            "## Table of Contents\n\n- [Plans](#plans)\n\n"
            f"## Plans\n\n{header}\n{body}\n")


_PHDR = ("| Repo | Plan | Status | Priority | Age | Flags |\n"
         "|---|---|---|---|---|---|")


def _prow(item, today) -> str:
    flags = ", ".join(item.flags) if item.flags else "--"
    return (f"| {item.repo} | {item.title} | {item.status} | {_prio(item)} "
            f"| {_age(item, today)} | {flags} |")


def _psection(all_items, today, predicate) -> str:
    rows = [_prow(i, today) for i in sorted(
        (i for i in all_items if predicate(i)), key=_sort_key)]
    return _PHDR + "\n" + ("\n".join(rows) if rows else
                           "| -- | -- | -- | -- | -- | -- |")


def render_portfolio(items_by_repo, today) -> str:
    all_items = [i for items in items_by_repo.values() for i in items]
    repo_links = "\n".join(f"- [{r}]({r}.md)" for r in items_by_repo) or "_none_"
    toc = ("## Table of Contents\n\n"
           "- [Per-repo indexes](#per-repo-indexes)\n"
           "- [Pending](#pending)\n"
           "- [Implemented but not archived](#implemented-but-not-archived)\n"
           "- [Stale](#stale)\n"
           "- [Needs frontmatter](#needs-frontmatter)\n")
    return (
        f"# Manyfold Solution -- Plan Portfolio\n\n{_banner(today)}\n\n{toc}\n"
        f"## Per-repo indexes\n\n{repo_links}\n\n"
        "## Pending\n\n"
        f"{_psection(all_items, today, lambda i: i.status in model.ACTIVE_STATUSES)}\n\n"
        "## Implemented but not archived\n\n"
        f"{_psection(all_items, today, lambda i: 'implemented-not-archived' in i.flags)}\n\n"
        "## Stale\n\n"
        f"{_psection(all_items, today, lambda i: 'stale' in i.flags)}\n\n"
        "## Needs frontmatter\n\n"
        f"{_psection(all_items, today, lambda i: 'needs-frontmatter' in i.flags)}\n")
