import contextlib
import io
import os
import subprocess
import tempfile
import unittest
from datetime import date
from pathlib import Path

import generate


def _main(args):
    with contextlib.redirect_stdout(io.StringIO()):
        return generate.main(args)


def _args(tmp, pdir):
    return ["--repos", os.path.join(tmp, "repos.txt"), "--root", tmp, "--out", pdir]


class CheckMode(unittest.TestCase):
    def _with_portfolio_dir(self, fn):
        with tempfile.TemporaryDirectory() as tmp:
            pdir = os.path.join(tmp, "docs", "portfolio")
            # The repo list is private to an installation; the tests carry their own.
            with open(os.path.join(tmp, "repos.txt"), "w") as fh:
                fh.write("umbrella\n")
            os.makedirs(pdir)
            return fn(pdir, _args(tmp, pdir))

    def test_every_location_is_an_argument(self):
        # Nothing is derived from where the script lives: a checkout that holds it may be
        # public, and the pages carry repository names.
        for missing in (["--root", "/r", "--out", "/o"], ["--repos", "/f", "--out", "/o"], ["--repos", "/f", "--root", "/r"]):
            with self.assertRaises(SystemExit), contextlib.redirect_stderr(io.StringIO()):
                generate.main(missing)

    def test_committed_date_reads_stamp(self):
        def run(pdir, _):
            with open(os.path.join(pdir, "PORTFOLIO.md"), "w") as fh:
                fh.write("<!-- generated by x -- do not edit; generated 2026-08-01 -->\n")
            return generate._committed_date(pdir, date(2026, 8, 23))
        self.assertEqual(self._with_portfolio_dir(run), date(2026, 8, 1))

    def test_committed_date_falls_back_to_today(self):
        today = date(2026, 8, 23)
        self.assertEqual(self._with_portfolio_dir(lambda p, _: generate._committed_date(p, today)), today)

    def test_check_is_clean_right_after_generate_and_writes_nothing(self):
        def run(pdir, args):
            self.assertEqual(_main(args), 0)
            before = {f: os.stat(os.path.join(pdir, f)).st_mtime_ns for f in os.listdir(pdir)}
            self.assertEqual(_main(args + ["--check"]), 0)
            after = {f: os.stat(os.path.join(pdir, f)).st_mtime_ns for f in os.listdir(pdir)}
            self.assertEqual(before, after)
            return True
        self.assertTrue(self._with_portfolio_dir(run))

    def test_check_reports_drift_and_writes_nothing(self):
        def run(pdir, args):
            self.assertEqual(_main(args), 0)
            path = os.path.join(pdir, "PORTFOLIO.md")
            with open(path, "a") as fh:
                fh.write("\nstale line\n")
            mtime = os.stat(path).st_mtime_ns
            self.assertEqual(_main(args + ["--check"]), 1)
            self.assertEqual(os.stat(path).st_mtime_ns, mtime)
            with open(path) as fh:
                self.assertIn("stale line", fh.read())
            return True
        self.assertTrue(self._with_portfolio_dir(run))


class CheckModeGitPreservation(unittest.TestCase):
    """Exercise real rendering against dirty generated files in disposable repos."""

    def _git(self, *args):
        return subprocess.check_output(
            ["git", "-C", str(self.repo), *args],
            env={**os.environ, "GIT_OPTIONAL_LOCKS": "0"},
            stderr=subprocess.PIPE,
        )

    def _snapshot(self):
        return {
            "files": {
                str(path.relative_to(self.pdir)): (
                    path.read_bytes(), path.stat().st_mtime_ns
                )
                for path in self.pdir.rglob("*") if path.is_file()
            },
            "index": (self.repo / ".git/index").read_bytes(),
            "entries": self._git("ls-files", "--stage", "-z"),
            "staged": self._git("diff", "--cached", "--binary"),
            "unstaged": self._git("diff", "--binary"),
            "status": self._git("status", "--porcelain=v1", "-z", "--untracked-files=all"),
        }

    def _assert_preserved(self, drift):
        for state in ("unstaged", "staged", "partially-staged", "untracked"):
            with self.subTest(state=state), tempfile.TemporaryDirectory() as tmp:
                self.repo = Path(tmp) / "manyfold"
                self.pdir = self.repo / "docs/portfolio"
                self.pdir.mkdir(parents=True)
                source = Path(tmp) / "fixture/docs/plans/example.md"
                source.parent.mkdir(parents=True)
                source.write_text("# Original fixture plan\n", encoding="utf-8")
                self._git("init", "--quiet")
                # Ignore host hooks/signing; fixtures never contact a remote.
                self._git("config", "core.hooksPath", str(Path(tmp) / "no-hooks"))
                self._git("config", "commit.gpgSign", "false")
                self._git("config", "user.name", "Portfolio Fixture")
                self._git("config", "user.email", "fixture@example.invalid")
                repos = Path(tmp) / "repos.txt"
                repos.write_text("fixture\n", encoding="utf-8")
                args = ["--repos", str(repos), "--root", tmp, "--out", str(self.pdir)]
                self.assertEqual(_main(args), 0)
                for name in ("unstaged-notes.md", "staged-notes.md"):
                    (self.pdir / name).write_bytes(b"Original notes\n")
                self._git("add", "docs/portfolio")
                self._git("commit", "--quiet", "-m", "Initial fixture")

                # A source change makes fresh output differ from HEAD while
                # still allowing --check to succeed on dirty generated files.
                source.write_text("# Updated fixture plan\n", encoding="utf-8")
                self.assertEqual(_main(args), 0)
                target = self.pdir / "PORTFOLIO.md"
                if drift:
                    with target.open("ab") as fh:
                        fh.write(b"\nPre-existing manual edit\n")
                if state == "staged":
                    self._git("add", "docs/portfolio/PORTFOLIO.md")
                elif state == "partially-staged":
                    working_bytes = target.read_bytes()
                    target.write_bytes(working_bytes + b"Staged-only edit\n")
                    self._git("add", "docs/portfolio/PORTFOLIO.md")
                    target.write_bytes(working_bytes)
                elif state == "untracked":
                    self._git("rm", "--cached", "--quiet", "docs/portfolio/PORTFOLIO.md")

                (self.pdir / "unstaged-notes.md").write_bytes(b"Unrelated working edit\n")
                (self.pdir / "staged-notes.md").write_bytes(b"Unrelated staged edit\n")
                self._git("add", "docs/portfolio/staged-notes.md")
                (self.pdir / "untracked").mkdir()
                (self.pdir / "untracked/local.bin").write_bytes(b"\x00\xffLocal content\n")
                before = self._snapshot()
                # Prove the fixture actually contains the requested Git states.
                target_status = {
                    "unstaged": b" M", "staged": b"M ",
                    "partially-staged": b"MM", "untracked": b"??",
                }[state]
                self.assertIn(target_status + b" docs/portfolio/PORTFOLIO.md\0", before["status"])
                self.assertIn(b" M docs/portfolio/unstaged-notes.md\0", before["status"])
                self.assertIn(b"M  docs/portfolio/staged-notes.md\0", before["status"])
                self.assertIn(b"?? docs/portfolio/untracked/local.bin\0", before["status"])

                output = io.StringIO()
                with contextlib.redirect_stdout(output):
                    result = generate.main(args + ["--check"])
                self.assertEqual(result, 1 if drift else 0)
                self.assertIn("DRIFT: 1 page(s)" if drift else "OK:", output.getvalue())
                self.assertEqual(before, self._snapshot())

    def test_success_preserves_dirty_portfolio_and_index(self):
        self._assert_preserved(drift=False)

    def test_drift_preserves_dirty_portfolio_and_index(self):
        self._assert_preserved(drift=True)


if __name__ == "__main__":
    unittest.main()
